name: travelplanner
services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/
    env_file:
      - .env
    networks:
      - appnet
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ../log:/log

  mongo:
    image: mongo:8.0
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: >
        ["CMD", "mongosh", "--quiet", "--eval",
         "try { rs.status().ok } catch(e) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongo:27017'}]}).ok }"]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 10s
    networks:
      - appnet
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

networks:
  appnet:
    driver: bridge

volumes:
  mongo_data:
